feat: マッピング先のアクションクラス名とメソッド名をリクエストスコープに保存するように修正
nablarch/nablarch-router-adaptor pull request #12
Opened 2020-09-16 06:11 UTC by opengl-8080

- 解決したマッピング先のクラス名とメソッド名を、リクエストスコープに保存する修正を追加
    - 現時点での用途は、 nablarch-micrometer-adaptor で取得してリクエスト処理時間のメトリクスのタグとして設定するため
- `RoutesMapping` と `PathOptionsProviderRoutesMapping` の２つを修正
- リクエストスコープに設定するときのデフォルトのキー名は `RoutesMapping` に定数として宣言して、 `PathOptionsProviderRoutesMapping` から利用するようにした
    - ２つのクラスが共通で利用していて、かつこの定数を配置するのにふさわしそうなクラスが見当たらなかったため

2020-09-16 06:56 UTC, backpaper0 requested changes

2020-09-16 06:56 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/PathOptionsProviderRoutesMapping.java
> +    private String requestMappingClassVarName = RoutesMapping.DEFAULT_REQUEST_MAPPING_CLASS_VAR_NAME;
せっかく`RoutesMapping`に依存していないのに定数のために依存するのは微妙ですね、、、

2020-09-17 04:07 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/PathOptionsProviderRoutesMapping.java
> +    private String requestMappingClassVarName = RoutesMapping.DEFAULT_REQUEST_MAPPING_CLASS_VAR_NAME;
確かにそうですね。
定数はそれぞれのクラスで定義しますか。

2020-09-17 05:21 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/PathOptionsProviderRoutesMapping.java
> +    private String requestMappingClassVarName = RoutesMapping.DEFAULT_REQUEST_MAPPING_CLASS_VAR_NAME;
それで良いです。

2020-09-18 04:04 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/PathOptionsProviderRoutesMapping.java
> +    private String requestMappingClassVarName = RoutesMapping.DEFAULT_REQUEST_MAPPING_CLASS_VAR_NAME;
定数をそれぞれのクラスで宣言するように修正しました。

https://github.com/nablarch/nablarch-router-adaptor/pull/12/commits/928c20b15c08623f71c83711c6211302a7fc2edf

2020-09-18 06:08 UTC, backpaper0 approved these changes

2020-09-18 07:05 UTC, opengl-8080 commented
本機能の5u18リリースは見送りになったので、プルリクエストをクローズします。

2020-09-18 07:05 UTC, closed without merging