Pathアノテーションでルーティングを登録できる仕組みを追加
nablarch/nablarch-router-adaptor pull request #7
Opened 2020-07-14 08:02 UTC by opengl-8080

2020-07-14 11:47 UTC, backpaper0 requested changes

2020-07-14 11:47 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +            for (Method method : clazz.getDeclaredMethods()) {
JAX-RSの仕様的にはクラスに`Path`アノテーションが必須なので、そこに合わせてしまって良いんじゃないかと思いました。

2020-07-14 11:47 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +                Class<?> clazz = this.getClass().getClassLoader().loadClass(packageName + "." + className);
クラスローダーは毎回同じインスタンスになるからコンストラクタで取得するか、外から渡すのが良いと思います。

2020-07-14 11:47 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +            for (Method method : clazz.getDeclaredMethods()) {
というかこれだと次のようなクラスが受け入れられてしまう気がしますね。

```
public class Hoge {
    @GET
    public void fuga() {
    }
}
```

2020-07-14 11:47 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +public class JaxRsResourceFinder {
インスタンス変数を持たない、とても関数的なクラスだなと思いました。
こういうクラスの存在って気持ちが落ち着かないんですよね。

いくつかのメソッドを`override`可能にしておけばまだクラスである意義が見出せそうな気がします。

2020-07-14 11:47 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/ClassTraversalRoutesMapping.java
> +                request.setParam(option.getKey(), option.getValue().toString());
`RoutesMapping`をみると`controller`と`action`を除いていますが、それは踏襲しなくて大丈夫ですか？

それと`RoutesMapping`では`getValue`の`null`チェックをしていますが、そちらも踏襲しなくて大丈夫ですか？

2020-07-14 11:47 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsPathStringParser.java
> +    private PathRequirements buildRouterRequirements(Class<?> resourceClass, Method resourceMethod) {
`String`を受け取って`PathRequirements`を返す処理は別クラスに切り出した方が良いと思います。
その方がテストケースと合わせて見やすい。

2020-07-14 11:47 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +                    methodList.add(method);
次のようなメソッドも受け入れてしまいそうに見えます。JAX-RS的にはHTTPを表すアノテーションは1つしか付けてはいけないはずなので、それに準じてください。

```
@GET
@POST
public String method() {}
```

2020-07-15 06:27 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +            for (Method method : clazz.getDeclaredMethods()) {
クラスに `Path` がついているクラスのみを対象にするように修正しました。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/9b5de1f18b31b6aa9cc8d8055a80f088b82d2975

2020-07-15 06:27 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +                Class<?> clazz = this.getClass().getClassLoader().loadClass(packageName + "." + className);
インスタンス生成時にクラスローダを保持しておくように修正しました。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/6d80582b6ea839f8e7880ea88cd56e145af54d9a

2020-07-15 06:30 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +public class JaxRsResourceFinder {
`override` させる意味のありそうな形でメソッド分けする方法が思いつかなかったので、試しにクラスをトラバースしてリソースクラスを収集するクラスを外部から切り替えられる余地を与えてみました。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/8056a00bc0fa95a94e8ebccd2440dbc9730b13e8

2020-07-15 06:32 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/ClassTraversalRoutesMapping.java
> +                request.setParam(option.getKey(), option.getValue().toString());
大丈夫ではなさそうなので `controller`, `action` を取り除いて、 `null` チェックを足しました。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/90dac02dbf57ae8ae425a5f87689ce52c400bda2

2020-07-15 06:38 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsPathStringParser.java
> +    private PathRequirements buildRouterRequirements(Class<?> resourceClass, Method resourceMethod) {
`Path` 文字列を解析するクラスを `JaxRsPathParser` として抽出しました。
もともとあった `JaxRsPathStringParser` は、 `JaxRsRouterConverter` にリネームしました。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/db3e09db43d096628afc4055bf8a315cdd654304

抽出した結果、 `JaxRsPathParser` がインスタンス変数を持たない関数的なクラスになってしまいましたが、 `JaxRsRouterConverter` をテストするときに `JaxRsPathParser` をモック化してテストを簡略化できるようにしているので、一応クラス化の意味はあるのかなと考えていますがいかがでしょう。。。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/db3e09db43d096628afc4055bf8a315cdd654304#diff-f8b5e66f6f25b2f527aeb2cd3faa47eaR164

2020-07-15 06:39 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +                    methodList.add(method);
HTTP メソッドを指定するアノテーションが２つ以上設定されていた場合はエラーにするように修正しました。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/09cc8b2cc21f66779adf7bd530156f69da59f56d

2020-07-15 08:10 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +public class JaxRsResourceFinder {
リソースクラス・メソッドを自由に定義できそうだと思いましたが、パスを構築する時にはメソッドに`@Path`があるか確認するし、微妙な気がしました。

指摘コメントは取り下げます。`git revert`しておいてください。

2020-07-15 08:13 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsPathStringParser.java
> +    private PathRequirements buildRouterRequirements(Class<?> resourceClass, Method resourceMethod) {
これはどちらかというと`JaxRsRouterConverter`に対する指摘になりますが、`setJaxRsPathParser`がテストのためだけにあるのであれば、このメソッドはなくしてしまって`JaxRsPathParser`はコンストラクタで受け取れるようにした方が良いと思いました。

2020-07-15 08:16 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +public class JaxRsResourceFinder {
より拡張性を持たせるのであれば、次のように`ClassTraversalOptionsCollector.collect`から`basePackage`を取り除くのが一番な気がしました。

https://github.com/backpaper0/nablarch-router-adaptor/commit/ea661a25182f7c23ecbbb8304a32d5a31a7a04d7

こうしておくと`ClassTraversalOptionsCollector`の実装を切り替えれば好きにルーティングを組み立てることができます。
※この場合`ClassTraversalOptionsCollector`というクラス名は不適当なので`PathOptionsProvider`とかの方が良さそう
※元々の`routes.xml`を読み込む仕組みもそのような作りになっていれば拡張性があってよかったのになぁ

2020-07-15 08:17 UTC, backpaper0 requested changes
見ました。

2020-07-16 00:42 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +public class JaxRsResourceFinder {
revert しました。
https://github.com/nablarch/nablarch-router-adaptor/commit/b7421b0200a326eb275a35cb98ef8be2d3637310

> より拡張性を持たせるのであれば、次のようにClassTraversalOptionsCollector.collectからbasePackageを取り除くのが一番な気がしました。

なるほどです。
今からでもやってみますか？（`ClassTraversalRoutesMapping` の名前を何としようかがちょっと悩みどころですが）

2020-07-16 00:44 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsPathStringParser.java
> +    private PathRequirements buildRouterRequirements(Class<?> resourceClass, Method resourceMethod) {
コンストラクタで指定するようにするとコンポーネント定義のxmlが書けなくて困るかなと思って setter にしていましたが、
改めて見直したら `JaxRsRouterConverter` は `JaxRsOptionsCollector` 内部で new していたので関係ありませんでした。

コンストラクタから設定できるように修正しました。

https://github.com/nablarch/nablarch-router-adaptor/commit/37d53d137aed0e40e70e4a28d17caf09af1bb136

2020-07-16 01:07 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +public class JaxRsResourceFinder {
やりましょう。`ClassTraversalRoutesMapping`の名前は確かにそうですね。まあ悩んでみましょうか（みんなを巻き込んでみんなで悩んでもいいし）。

2020-07-16 01:09 UTC, backpaper0 commented on src/main/java/nablarch/integration/router/ClassTraversalRoutesMapping.java
> +        String path = ((ServletExecutionContext) executionContext).getHttpRequest().getRequestPath();
`RoutesMapping`は`instanceof ServletExecutionContext`して分岐していますね。踏襲しておきましょう。

2020-07-16 01:10 UTC, backpaper0 requested changes
みました。

2020-07-16 08:19 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/ClassTraversalRoutesMapping.java
> +        String path = ((ServletExecutionContext) executionContext).getHttpRequest().getRequestPath();
`ServletExecutionContext` でない場合の処理を追加しました。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/29bdae1380461a47497c611165700887cad21238

改めて見直してみると、他にも踏襲できていないところがあったので、以下２つの修正を追加しています。

* [baseUri が '/' で終わっていた場合にパスを補完する処理を追加](https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/67f4608acd6cb2f5af6b2577377cfe7d7f1a31d9)
* [MethodBinderFactoryが設定されていない場合はデフォルトでRoutesMethodBinderFactoryを使用](https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/f4a171e246b30169ba6bad2dbaa2b5d18b5d7dfb)

2020-07-16 08:21 UTC, opengl-8080 commented on src/main/java/nablarch/integration/router/jaxrs/JaxRsResourceFinder.java
> +public class JaxRsResourceFinder {
修正しました。

https://github.com/nablarch/nablarch-router-adaptor/pull/7/commits/7cedc4e9707f7d0ed99cc302edc38baaad1e6bdd

2020-07-17 01:58 UTC, backpaper0 approved these changes

2020-07-17 02:00 UTC, merged